name: Reusable mkdocs deploy

on:
  workflow_call:
    inputs:
      deploy_repo:
        required: true
        type: string
      mkdocs_config_location:
        required: true
        type: string
        default: './website/mkdocs.yml'
      nojekyll_location:
        required: true
        type: string
        default: './website/docs/.nojekyll'
    secrets:
      auth_token:
        required: true  
        
jobs:

  deploy-mkdocs:
  
    name: Pass input and secrets to my-action
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2.3.4
      
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install MarkdownHighlight
          python3 -m pip install https://codeload.github.com/mkdocs/mkdocs-bootstrap/zip/master

      - name: Build
        run: |
          mkdocs build --config-file ${{ inputs.mkdocs_config_location }} 
          touch ${{ inputs.nojekyll_location }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.auth_token }}
          publish_dir: ./website/docs
          external_repository: ${{ inputs.deploy_repo }}